# Generated by Django 4.0.1 on 2022-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_intakedata_carbs_intakedata_fats_intakedata_fiber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField()),
                ('counts', models.IntegerField()),
            ],
        ),
    ]
